
const { promisify } = require('util');
const {
  availableFormats,
  writeText,
  writeRTF,
  writeImage,
  writeHTML,
  writeFindText,
  writeBuffer,
  writeBookmark,
  write,
  readText,
  readRTF,
  readImage,
  readHTML,
  readFindText,
  readBuffer,
  readBookmark,
  read,
  has,
  // clear,

} = require('electron').clipboard;
const {
  readFilePaths,
  writeFilePaths,
  clear,
  saveImageAsJpegSync,
  saveImageAsJpegAsync,
  saveImageAsPngSync,
  saveImageAsPngAsync,
  putImageSync,
  putImageAsync,
  hasImage,
  // } = require('node-gyp-build')(__dirname);
} = require('./dist/batch-clipboard-xh.node');

module.exports = {
  readFilePaths,
  writeFilePaths,
  clear,
  saveImageAsJpeg: promisify(saveImageAsJpegAsync),
  saveImageAsJpegSync,
  saveImageAsPng: promisify(saveImageAsPngAsync),
  saveImageAsPngSync,
  putImageSync,
  putImage: promisify(putImageAsync),
  hasImage,
  availableFormats,
  writeText,
  writeRTF,
  writeImage,
  writeHTML,
  writeFindText,
  writeBuffer,
  writeBookmark,
  write,
  readText,
  readRTF,
  readImage,
  readHTML,
  readFindText,
  readBuffer,
  readBookmark,
  read,
  has,
};
